topics:
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "f"
    replication_factor : 1
    partition_size : 1
  - name: "a"
    replication_factor : 1
    partition_size : 1
  - name: "b"
    replication_factor : 1
    partition_size : 1
  - name: "c"
    replication_factor : 1
    partition_size : 1
  - name: "d"
    replication_factor : 1
    partition_size : 1
  - name: "e"
    replication_factor : 1
    partition_size : 1
  - name: "faz"
    replication_factor : 1
    partition_size : 1
  - name: "faz1"
    replication_factor : 1
    partition_size : 1
  - name: "faz123"
    replication_factor : 1
    partition_size : 1